import jsPDF from 'jspdf'

/**
 * Generate a PDF from the doctor report text and trigger a browser download.
 * PDF is generated entirely client-side — no backend call is made.
 */
export function downloadReport(reportText: string, periodLabel: string): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const marginLeft = 18
  const marginRight = 18
  const marginTop = 22
  const marginBottom = 22
  const contentWidth = pageWidth - marginLeft - marginRight

  const today = new Date()
  const dateStr = today.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
  const fileDate = today.toISOString().slice(0, 10) // YYYY-MM-DD

  let y = marginTop

  // ── Header bar ─────────────────────────────────────────────────────────────
  doc.setFillColor(78, 124, 92) // --accent green
  doc.rect(0, 0, pageWidth, 16, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(255, 255, 255)
  doc.text('HealthSignal', marginLeft, 10.5)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text('AI · not medical advice', pageWidth - marginRight, 10.5, { align: 'right' })

  y = 24

  // ── Report title ───────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.setTextColor(25, 33, 46) // --ink
  doc.text('Health Report', marginLeft, y)
  y += 7

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(90, 100, 117) // --sub
  doc.text(`Covering ${periodLabel.toLowerCase()}  ·  Generated ${dateStr}`, marginLeft, y)
  y += 4

  // Divider
  doc.setDrawColor(220, 214, 200)
  doc.line(marginLeft, y, pageWidth - marginRight, y)
  y += 8

  // ── Report body ────────────────────────────────────────────────────────────
  const lines = reportText.split('\n')

  for (const rawLine of lines) {
    const line = rawLine.trimEnd()

    // Page overflow — add new page with continuation header
    if (y > pageHeight - marginBottom - 12) {
      addFooter(doc, pageWidth, pageHeight, marginLeft, marginRight, dateStr)
      doc.addPage()
      y = marginTop

      doc.setFont('helvetica', 'bold')
      doc.setFontSize(9)
      doc.setTextColor(140, 149, 166)
      doc.text('Health Report (continued)', marginLeft, y)
      y += 6

      doc.setDrawColor(220, 214, 200)
      doc.line(marginLeft, y, pageWidth - marginRight, y)
      y += 6
    }

    if (!line.trim()) {
      y += 3
      continue
    }

    // Section header: ## Header or ALL-CAPS line or ending with ":"
    if (line.match(/^#{1,3}\s/) || line.trim().match(/^[A-Z][A-Z\s\d–-]+:?\s*$/)) {
      y += 2
      const headerText = line.trim().replace(/^#{1,3}\s/, '').replace(/:$/, '')

      doc.setFont('helvetica', 'bold')
      doc.setFontSize(12)
      doc.setTextColor(25, 33, 46)
      doc.text(headerText, marginLeft, y)
      y += 2

      doc.setDrawColor(235, 229, 218)
      doc.line(marginLeft, y, pageWidth - marginRight, y)
      y += 5
      continue
    }

    // Bullet point
    if (line.trim().startsWith('- ') || line.trim().startsWith('• ')) {
      const bulletText = line.trim().replace(/^[-•]\s/, '')
      const bulletIndent = marginLeft + 5

      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10)
      doc.setTextColor(39, 49, 63)

      // Bullet dot
      doc.setFillColor(78, 124, 92)
      doc.circle(marginLeft + 1.5, y - 1.3, 0.9, 'F')

      const wrappedBullet = doc.splitTextToSize(bulletText, contentWidth - 7)
      doc.text(wrappedBullet, bulletIndent, y)
      y += wrappedBullet.length * 5 + 1
      continue
    }

    // Regular paragraph
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(39, 49, 63)
    const wrapped = doc.splitTextToSize(line, contentWidth)
    doc.text(wrapped, marginLeft, y)
    y += wrapped.length * 5 + 1
  }

  // ── Footer on last page ────────────────────────────────────────────────────
  addFooter(doc, pageWidth, pageHeight, marginLeft, marginRight, dateStr)

  // ── Download ───────────────────────────────────────────────────────────────
  doc.save(`health-report-${fileDate}.pdf`)
}

function addFooter(
  doc: jsPDF,
  pageWidth: number,
  pageHeight: number,
  marginLeft: number,
  marginRight: number,
  dateStr: string,
): void {
  const y = pageHeight - 12

  doc.setDrawColor(220, 214, 200)
  doc.line(marginLeft, y - 3, pageWidth - marginRight, y - 3)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(140, 149, 166)
  doc.text(`Generated by HealthSignal on ${dateStr}`, marginLeft, y)
  doc.text(
    'AI-generated summary · not medical advice · confirm all findings with a clinician',
    pageWidth - marginRight,
    y,
    { align: 'right' },
  )
}
